(function () {
  "use strict";
  const money = new Intl.NumberFormat("hu-HU", { maximumFractionDigits: 0 });
  const fmt = value => `${money.format(Math.round(Number(value) || 0))} Ft`;
  const num = value => Math.max(0, Number(value) || 0);
  const signed = value => Number(value) || 0;
  const moneyNum = value => { const raw=String(value??"").replace(/[\s\u00a0]/g,""); if(/^-?\d{1,3}([.,]\d{3})+$/.test(raw))return Number(raw.replace(/[.,]/g,""))||0; return Number(raw.replace(",","."))||0; };
  const esc = value => String(value ?? "").replace(/[&<>'"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
  const id = () => `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`;
  const defaults = [
    ["mark","Márk",31000,true,20000,40000],["gabor","Gábor",28000,false,20000,40000],
    ["attila","Attila",26000,false,20000,40000],["adam","Ádám",24000,true,20000,60000],
    ["gyula","Gyula",22000,false,20000,40000],["bendeguz","Bendegúz",25000,true,0,0],
    ["agi","Ági",16000,true,0,0],["tamas","Tamás",40000,false,20000,40000]
  ].map(([employeeId,name,dailyRate,cashier,workwearMonthly,winterMonthly]) => ({employeeId,name,dailyRate,hourlyRate:dailyRate/8,overtimeRate:5000,vacationAllowance:5,cashier,workwearMonthly,winterMonthly}));
  let state = PayrollStorage.load() || {version:1,employees:defaults,weeks:{},funds:{},creditedMonths:{},events:[]};
  state.events ||= [];if(!state.baseDaysV2){Object.values(state.weeks||{}).forEach(week=>Object.values(week).forEach(record=>{if(Number(record.days)===0)record.days=5}));state.baseDaysV2=true}
  let weekStart = fridayFor(new Date());
  function migrateState(data){
    let changed=false;data.events||=[];data.weeks||={};data.funds||={};
    if(!data.dailyFundsV1){(data.employees||[]).forEach(e=>{e.workwearMonthly=num(e.workwearMonthly)>0?1000:0;e.winterMonthly=num(e.winterMonthly)>0?2000:0});data.fundAccrualStart=iso(weekStart);data.dailyFundsV1=true;changed=true}
    if(!data.paidLeaveV1){data.events.filter(event=>event.type==="paid-leave"&&event.effect?.vacation&&!event.effect.days).forEach(event=>{const key=iso(fridayFor(new Date(`${event.date}T12:00:00`))),record=data.weeks[key]?.[event.employeeId];if(record)record.days=Math.max(0,num(record.days)-1);event.effect.days=-1});data.paidLeaveV1=true;changed=true}
    if(!data.agiNameV1){const agi=(data.employees||[]).find(e=>e.employeeId==="agi")||(data.employees||[]).find(e=>String(e.name||"").trim().toLocaleLowerCase("hu-HU")==="anya");if(agi){agi.name="Ági";data.events.filter(event=>event.employeeId===agi.employeeId).forEach(event=>event.employeeName="Ági")}data.agiNameV1=true;changed=true}
    if(!data.pdfStart20260910){
      const employeeData={mark:{dailyRate:31000,hourlyRate:3875,vacationAllowance:5,vacationOpening:3},gabor:{dailyRate:28000,hourlyRate:3500,vacationAllowance:5,vacationOpening:2},attila:{dailyRate:26000,hourlyRate:3250,vacationAllowance:5,vacationOpening:3},adam:{dailyRate:24000,hourlyRate:3000,vacationAllowance:5,vacationOpening:5},gyula:{dailyRate:22000,hourlyRate:2750,vacationAllowance:5,vacationOpening:4},bendeguz:{dailyRate:25000,hourlyRate:3125,vacationAllowance:3,vacationOpening:0},agi:{dailyRate:16000,hourlyRate:2000,vacationAllowance:5,vacationOpening:0},tamas:{dailyRate:40000,hourlyRate:5000,vacationAllowance:5,vacationOpening:0}};
      Object.entries(employeeData).forEach(([employeeId,values])=>{const employee=(data.employees||[]).find(e=>e.employeeId===employeeId);if(employee)Object.assign(employee,values,{overtimeRate:5000,vacationOpeningYear:2026})});
      const week=data.weeks["2026-09-04"]||={},base=(employeeId,days=5)=>({days,hours:0,overtime:0,vacation:0,advance:0,loan:0,repayment:0,payback:0,bonuses:[],others:[],cashbox:employeeData[employeeId]&&["mark","adam","agi","bendeguz"].includes(employeeId)?{topup:0,withdrawal:0}:null});
      week.tamas=base("tamas");week.gyula=base("gyula");week.gabor={...base("gabor",4),vacation:1};week.attila=base("attila");week.mark={...base("mark"),debtOpening:297176,repayment:40000,cashbox:{topup:0,withdrawal:335000}};week.adam={...base("adam"),debtOpening:301000,others:[{id:"pdf-2026-09-04-adam-opel",label:"Opel",amount:15000}],cashbox:{topup:35000,withdrawal:0}};week.agi={...base("agi"),debtOpening:80000,repayment:10000,others:[{id:"pdf-2026-09-04-agi-uzemanyag",label:"Üzemanyag",amount:10000}],cashbox:{topup:0,withdrawal:0}};week.bendeguz=base("bendeguz",0);data.weeks["2026-09-04"]=week;
      data.pdfStart20260910=true;changed=true;
    }
    if(!data.vacationPdfV2){const gabor=(data.employees||[]).find(e=>e.employeeId==="gabor");if(gabor){gabor.vacationOpening=2;gabor.vacationOpeningYear=2026}data.vacationPdfV2=true;changed=true}
    if(!data.vacationPdfV3){const gabor=(data.employees||[]).find(e=>e.employeeId==="gabor");if(gabor){gabor.vacationOpening=2;gabor.vacationOpeningYear=2026}data.vacationPdfV3=true;changed=true}
    return changed
  }
  if(migrateState(state))localStorage.setItem(PayrollStorage.key,JSON.stringify(state));

  function fridayFor(date) { const d = new Date(date); d.setHours(12,0,0,0); const day=d.getDay(); const diff=(day-5+7)%7; d.setDate(d.getDate()-diff); return d; }
  function iso(date) { return date.toISOString().slice(0,10); }
  function addDays(date, days) { const d=new Date(date); d.setDate(d.getDate()+days); return d; }
  function huDate(date) { return date.toLocaleDateString("hu-HU",{month:"2-digit",day:"2-digit"}); }
  function activeEmployees(){return state.employees.filter(e=>e.active!==false)}
  function emptyWeek(employee) { return {days:5,hours:0,overtime:0,vacation:0,advance:0,loan:0,repayment:0,payback:0,bonuses:[],others:[],cashbox:employee.cashier?{topup:0,withdrawal:0}:null}; }
  function getWeek(key=iso(weekStart)) { state.weeks[key] ||= {}; activeEmployees().forEach(e => state.weeks[key][e.employeeId] ||= emptyWeek(e)); return state.weeks[key]; }
  function previousDebt(employeeId) { const keys=Object.keys(state.weeks).filter(k=>k<iso(weekStart)).sort(); if(!keys.length)return 0; return calc(employeeId,state.weeks[keys.at(-1)][employeeId]||{}).debt; }
  function usedVacation(employeeId, year) { const employee=state.employees.find(e=>e.employeeId===employeeId),opening=Number(employee?.vacationOpeningYear)===Number(year)?num(employee.vacationOpening):0;return opening+Object.entries(state.weeks).filter(([k])=>k.startsWith(String(year))).reduce((sum,[,w])=>sum+num(w[employeeId]?.vacation),0); }
  function sumItems(items) { return (items||[]).reduce((s,item)=>s+moneyNum(item.amount),0); }
  function previousCashboxKey(employeeId,key) { return Object.keys(state.weeks).filter(k=>k<key&&state.weeks[k]?.[employeeId]?.cashbox).sort().at(-1)||null; }
  function cashboxFigures(employeeId,record,key=iso(weekStart),seen=new Set()) {
    const cb=record.cashbox||{},previousKey=previousCashboxKey(employeeId,key);
    let opening=num(cb.opening);
    if(previousKey&&!cb.openingManual&&!opening&&!seen.has(previousKey)){seen.add(previousKey);opening=cashboxFigures(employeeId,state.weeks[previousKey][employeeId],previousKey,seen).next}
    const current=opening+num(cb.income)-num(cb.expense),next=current+signed(cb.correction);
    return {opening,current,next};
  }
  function calc(employeeId, record, key=iso(weekStart)) {
    const e=state.employees.find(x=>x.employeeId===employeeId); if(!e)return {};
    const dayPay=num(record.days)*num(e.dailyRate),vacationPay=num(record.vacation)*num(e.dailyRate),hourPay=num(record.hours)*num(e.hourlyRate),overtimePay=num(record.overtime)*num(e.overtimeRate);
    const bonus=sumItems(record.bonuses), other=sumItems(record.others), income=dayPay+vacationPay+hourPay+overtimePay+bonus+other;
    const additions=num(record.payback)+num(record.loan),deductions=num(record.advance)+num(record.repayment),cash=Math.max(0,income+additions-deductions);
    const oldDebt=record.debtOpening==null?previousDebtRaw(employeeId):num(record.debtOpening), debt=Math.max(0,oldDebt+num(record.loan)-num(record.repayment));
    const cb=record.cashbox||{},cashbox=cashboxFigures(employeeId,record,key),withdrawal=num(cb.withdrawal),totalCash=cash+num(cb.topup)-withdrawal;
    return {dayPay,vacationPay,hourPay,overtimePay,bonus,other,income,additions,deductions,cash,oldDebt,debt,current:cashbox.current,nextCash:cashbox.next,opening:cashbox.opening,withdrawal,totalCash};
  }
  function previousDebtRaw(employeeId) { const keys=Object.keys(state.weeks).filter(k=>k<iso(weekStart)&&state.weeks[k]?.[employeeId]).sort(); if(!keys.length)return 0; const r=state.weeks[keys.at(-1)][employeeId]||{}; const oldKey=weekStart; weekStart=new Date(keys.at(-1)+"T12:00:00"); const result=calc(employeeId,r).debt; weekStart=oldKey; return result; }
  function save(message) { PayrollStorage.save(state); if(message)toast(message); }
  function toast(message){const el=document.getElementById("toast");el.textContent=message;el.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove("show"),2200)}
  document.addEventListener("focusin",event=>{const input=event.target;if(input.matches?.('input[type="number"]')&&signed(input.value)===0)input.value=""});
  document.addEventListener("focusout",event=>{const input=event.target;if(input.matches?.('input[type="number"]')&&input.value.trim()===""){input.value="0";input.dispatchEvent(new Event("input",{bubbles:true}))}});

  function renderWeek() {
    const end=addDays(weekStart,6), pay=addDays(end,1), key=iso(weekStart), records=getWeek(key);
    document.getElementById("weekRange").textContent=`${weekStart.getFullYear()}. ${huDate(weekStart)} – ${huDate(end)}`;
    document.getElementById("payday").textContent=`Fizetés: ${pay.toLocaleDateString("hu-HU")}, péntek`;
    document.getElementById("employeeCards").innerHTML=activeEmployees().map(e=>card(e,records[e.employeeId],key)).join("");
    document.querySelectorAll(".pay-card .pay-head").forEach(head=>head.insertAdjacentHTML("afterbegin",'<label class="card-selector"><input data-select-card type="checkbox"> Nyomtatásra</label>'));
    document.querySelectorAll(".pay-table [data-cash]").forEach(input=>input.closest("tr").classList.add("cashbox-field-row"));
    document.querySelectorAll(".pay-card").forEach(card=>{const record=records[card.dataset.employee];decoratePayCard(card,record);addItemSummary(card,record)});
    bindCards(); bindPrintSelection(); renderTotals();
  }
  function row(label,name,value,rate,total,cls="") { return `<tr class="${cls}"><td>${label}</td><td><input data-field="${name}" type="number" min="0" step="0.5" value="${value||0}" aria-label="${label}"></td><td class="number">${fmt(rate)}</td><td class="number pay-row-total" data-output="${name}Total">${fmt(total)}</td></tr>`; }
  function card(e,r,key) {
    const c=calc(e.employeeId,r,key), vac=usedVacation(e.employeeId,weekStart.getFullYear()), cashbox=e.cashier?`<tr class="cashbox-title"><td colspan="4"><b>Kassza</b></td></tr><tr class="cashbox-field-row"><td>Kasszafeltöltés</td><td colspan="2"><input data-cash="topup" type="text" inputmode="numeric" value="${num(r.cashbox?.topup)||""}" placeholder="0"></td><td class="number" data-cash-topup>${fmt(num(r.cashbox?.topup))}</td></tr><tr class="cashbox-field-row cashbox-withdrawal"><td>Kasszakivonás</td><td colspan="2"><input data-cash="withdrawal" type="text" inputmode="numeric" value="${num(r.cashbox?.withdrawal)||""}" placeholder="0"></td><td class="number" data-cash-withdrawal>${fmt(num(r.cashbox?.withdrawal))}</td></tr><tr class="cash-row"><td colspan="3">Pénteken átadandó teljes készpénz</td><td class="number" data-cash-total>${fmt(c.totalCash)}</td></tr>`:"";
    return `<article class="pay-card" data-employee="${e.employeeId}"><div class="pay-head"><h2>${esc(e.name)}</h2><div><strong>${weekStart.getFullYear()}</strong><small>${huDate(weekStart)} – ${huDate(addDays(weekStart,6))}</small></div></div><div class="summary-strip"><span>Nap<b data-output="days">${num(r.days)}</b></span><span>Felhasznált szabadság<b data-output="vacationSummary">${vac}/${e.vacationAllowance} nap</b></span><span>Készpénz<b data-output="cash">${fmt(c.cash)}</b></span></div><table class="pay-table"><thead><tr><th>Tétel</th><th>Db</th><th class="number">Bér</th><th class="number">Összesen</th></tr></thead><tbody>${row("Nap","days",r.days,e.dailyRate,c.dayPay)}${row("Óra","hours",r.hours,e.hourlyRate,c.hourPay)}${row("Túlóra","overtime",r.overtime,e.overtimeRate,c.overtimePay)}${row("Fizetett szabadság","vacation",r.vacation,e.dailyRate,num(r.vacation)*e.dailyRate)}<tr><td>Bónusz</td><td colspan="2"></td><td class="number pay-row-total" data-output="bonus">${fmt(c.bonus)}</td></tr><tr><td>Egyéb tétel</td><td colspan="2"></td><td class="number pay-row-total" data-output="other">${fmt(c.other)}</td></tr><tr class="income-row"><td colspan="3">Jövedelem</td><td class="number pay-row-total" data-output="income">${fmt(c.income)}</td></tr><tr><td>Visszafizetés (+)</td><td colspan="2"><input data-field="payback" type="number" min="0" value="${r.payback||0}"></td><td></td></tr><tr><td>Előleg (−)</td><td colspan="2"><input data-field="advance" type="number" min="0" value="${r.advance||0}"></td><td></td></tr><tr><td>Kölcsön (+)</td><td colspan="2"><input data-field="loan" type="number" min="0" value="${r.loan||0}"></td><td></td></tr><tr><td>Törlesztés (−)</td><td colspan="2"><input data-field="repayment" type="number" min="0" value="${r.repayment||0}"></td><td></td></tr><tr class="cash-row"><td colspan="3">Kifizetendő készpénz</td><td class="number" data-output="cash">${fmt(c.cash)}</td></tr><tr class="debt-row"><td>Korábbi tartozás</td><td class="number" data-output="oldDebt">${fmt(c.oldDebt)}</td><td>Fennmaradó tartozás</td><td class="number" data-output="debt">${fmt(c.debt)}</td></tr>${cashbox}</tbody></table><details class="details"><summary>Bónuszok és egyéb tételek szerkesztése</summary><div class="details-body"><h3>Bónuszok</h3><div class="item-list" data-list="bonuses">${itemRows(r.bonuses)}</div><button class="add-item" data-add="bonuses" type="button">+ Bónusz</button><h3>Egyéb tételek</h3><div class="item-list" data-list="others">${itemRows(r.others)}</div><button class="add-item" data-add="others" type="button">+ Egyéb tétel</button></div></details><div class="card-actions"><button class="button small print-action" data-print type="button">Nyomtatás</button><button class="button small email-action" data-email type="button">E-mail</button><button class="button small viber-action" data-viber type="button">Viber</button></div></article>`;
  }
  function itemLabel(item){const label=String(item?.label??"").trim();return label==="0"?"":label}
  function itemRows(items=[]) { return items.map(x=>`<div class="item-row" data-id="${x.id}"><input data-item="label" value="${esc(itemLabel(x))}" placeholder="Megnevezés" aria-label="Megnevezés"><input data-item="amount" type="text" inputmode="numeric" value="${moneyNum(x.amount)||""}" placeholder="Összeg" aria-label="Összeg"><button data-remove type="button" aria-label="Törlés">×</button></div>`).join(""); }
  function activeItems(items=[]){return items.filter(item=>moneyNum(item.amount))}
  function itemSummaryText(items=[]){return activeItems(items).map(item=>`${itemLabel(item)||"Tétel"}: ${fmt(moneyNum(item.amount))}`).join(" · ")}
  function updateItemSummary(card,type,items){const line=card.querySelector(`[data-item-summary="${type}"]`),text=itemSummaryText(items);line.hidden=!text;line.textContent=text}
  function addItemSummary(card,record){[["bonuses","bonus"],["others","other"]].forEach(([type,output])=>{const total=card.querySelector(`[data-output="${output}"]`),row=total.closest("tr"),line=document.createElement("small"),cell=row.children[1];row.classList.add(type==="bonuses"?"bonus-item-row":"other-item-row");cell.textContent="";line.className=`item-inline-summary ${type==="bonuses"?"bonus-summary":"other-summary"}`;line.dataset.itemSummary=type;cell.append(line);updateItemSummary(card,type,record[type]||[])})}
  function decoratePayCard(card,record){
    const labels={payback:"Visszafizetés (+)",advance:"Előleg (−)",loan:"Kölcsön (+)",repayment:"Törlesztés (−)"};
    Object.entries(labels).forEach(([field,label])=>{const input=card.querySelector(`[data-field="${field}"]`);if(input)input.closest("tr").children[0].textContent=label});
    const summary=card.querySelector(".summary-strip span:nth-child(2)");if(summary)summary.firstChild.textContent="Felhasznált szabadság";
    const debt=card.querySelector(".debt-row");if(debt){debt.children[0].textContent="Korábbi tartozás";debt.children[2].textContent="Fennmaradó tartozás"}
  }
  function setOutput(card,name,value){card.querySelectorAll(`[data-output="${name}"]`).forEach(element=>element.textContent=value)}
  function updatePayOutputs(card,employeeId,record){
    const employee=state.employees.find(x=>x.employeeId===employeeId),c=calc(employeeId,record),vac=usedVacation(employeeId,weekStart.getFullYear());
    setOutput(card,"days",num(record.days));setOutput(card,"vacationSummary",`${vac}/${employee.vacationAllowance} nap`);
    setOutput(card,"daysTotal",fmt(c.dayPay));setOutput(card,"hoursTotal",fmt(c.hourPay));setOutput(card,"overtimeTotal",fmt(c.overtimePay));setOutput(card,"vacationTotal",fmt(num(record.vacation)*num(employee.dailyRate)));
    setOutput(card,"bonus",fmt(c.bonus));setOutput(card,"other",fmt(c.other));setOutput(card,"income",fmt(c.income));setOutput(card,"cash",fmt(c.cash));setOutput(card,"oldDebt",fmt(c.oldDebt));setOutput(card,"debt",fmt(c.debt));
    updateItemSummary(card,"bonuses",record.bonuses||[]);updateItemSummary(card,"others",record.others||[]);
    const cashTotal=card.querySelector("[data-cash-total]");if(cashTotal){card.querySelector("[data-cash-topup]").textContent=fmt(num(record.cashbox?.topup));card.querySelector("[data-cash-withdrawal]").textContent=fmt(num(record.cashbox?.withdrawal));cashTotal.textContent=fmt(c.totalCash)}
    renderTotals();
  }
  function bindItemRow(card,row,employeeId,record,list){const item=record[list].find(x=>x.id===row.dataset.id);row.querySelectorAll("[data-item]").forEach(input=>input.addEventListener("input",()=>{item[input.dataset.item]=input.dataset.item==="amount"?moneyNum(input.value):input.value;save();updatePayOutputs(card,employeeId,record)}));row.querySelector("[data-remove]").onclick=()=>{record[list]=record[list].filter(x=>x.id!==row.dataset.id);row.remove();save();updatePayOutputs(card,employeeId,record)}}
  function bindCards(){document.querySelectorAll(".pay-card").forEach(card=>{const employeeId=card.dataset.employee,r=getWeek()[employeeId];card.querySelectorAll("[data-field]").forEach(input=>{input.addEventListener("input",()=>{r[input.dataset.field]=num(input.value);save();updatePayOutputs(card,employeeId,r)})});card.querySelectorAll("[data-cash]").forEach(input=>{input.addEventListener("input",()=>{r.cashbox||={topup:0,withdrawal:0};r.cashbox[input.dataset.cash]=moneyNum(input.value);save();updatePayOutputs(card,employeeId,r)})});card.querySelectorAll("[data-add]").forEach(button=>button.onclick=()=>{const list=button.dataset.add,item={id:id(),label:"",amount:0},container=card.querySelector(`[data-list="${list}"]`);r[list]||=[];r[list].push(item);container.insertAdjacentHTML("beforeend",itemRows([item]));const row=container.lastElementChild;bindItemRow(card,row,employeeId,r,list);save();updatePayOutputs(card,employeeId,r);row.querySelector("[data-item=label]").focus()});card.querySelectorAll(".item-row").forEach(row=>bindItemRow(card,row,employeeId,r,row.closest("[data-list]").dataset.list));card.querySelector("[data-print]").onclick=()=>printCard(card);card.querySelector("[data-email]").onclick=()=>share(employeeId,"email");card.querySelector("[data-viber]").onclick=()=>share(employeeId,"viber")})}
  function summaryText(employeeId){const e=state.employees.find(x=>x.employeeId===employeeId),r=getWeek()[employeeId],c=calc(employeeId,r),details=[...activeItems(r.bonuses).map(x=>`Bónusz – ${itemLabel(x)||"Tétel"}: ${fmt(x.amount)}`),...activeItems(r.others).map(x=>`Egyéb – ${itemLabel(x)||"Tétel"}: ${fmt(x.amount)}`)];return `Díszkertek munkabér – ${e.name}\n${huDate(weekStart)} – ${huDate(addDays(weekStart,6))}\n${details.length?details.join("\n")+"\n":""}Jövedelem: ${fmt(c.income)}\nVisszafizetés: +${fmt(r.payback)}\nKölcsön: +${fmt(r.loan)}\nLevonások: ${fmt(c.deductions)}\nKifizetendő készpénz: ${fmt(c.cash)}${e.cashier?`\nKasszafeltöltés: +${fmt(r.cashbox?.topup)}\nKasszakivonás: −${fmt(r.cashbox?.withdrawal)}\nÁtadandó összesen: ${fmt(c.totalCash)}`:""}`}
  function share(employeeId,type){const text=summaryText(employeeId),e=state.employees.find(x=>x.employeeId===employeeId);if(type==="email")location.href=`mailto:?subject=${encodeURIComponent(`Munkabér – ${e.name}`)}&body=${encodeURIComponent(text)}`;else location.href=`viber://forward?text=${encodeURIComponent(text)}`}
  function printCard(card){document.body.classList.add("print-single");card.classList.add("print-target");window.print();setTimeout(()=>{document.body.classList.remove("print-single");card.classList.remove("print-target")},400)}
  function bindPrintSelection(){document.querySelectorAll("[data-select-card]").forEach(input=>input.addEventListener("change",updatePrintSelection));updatePrintSelection()}
  function updatePrintSelection(){const boxes=[...document.querySelectorAll("[data-select-card]")],selected=boxes.filter(x=>x.checked).length;document.getElementById("selectedCount").textContent=`${selected} bérlap kijelölve`;document.getElementById("printSelected").disabled=!selected;document.getElementById("selectAllCards").checked=Boolean(boxes.length)&&selected===boxes.length;document.getElementById("selectAllCards").indeterminate=selected>0&&selected<boxes.length}
  function printGroup(all){const cards=[...document.querySelectorAll(".pay-card")];cards.forEach(card=>card.classList.toggle("print-target",all||card.querySelector("[data-select-card]").checked));document.body.classList.add("print-selected");window.print();setTimeout(()=>{document.body.classList.remove("print-selected");cards.forEach(card=>card.classList.remove("print-target"))},400)}
  function csvCell(value){let text=String(value??"");if(/^[=+\-@]/.test(text))text=`'${text}`;return `"${text.replace(/"/g,'""')}"`}
  function downloadPayroll(scope){const selected=iso(weekStart),year=weekStart.getFullYear(),month=String(weekStart.getMonth()+1).padStart(2,"0"),keys=Object.keys(state.weeks).filter(key=>scope==="week"?key===selected:scope==="month"?key.startsWith(`${year}-${month}`):key.startsWith(`${year}-`)).sort(),savedStart=weekStart,rows=[["Hét kezdete","Dolgozó","Nap","Felhasznált szabadság","Óra","Túlóra","Napidíj","Óradíj","Túlóradíj","Bónusz","Egyéb tétel","Jövedelem","Visszafizetés","Előleg","Kölcsön","Törlesztés","Kifizetendő készpénz","Kasszafeltöltés","Kasszakivonás","Átadandó összesen","Tartozás"]];try{keys.forEach(key=>{weekStart=new Date(`${key}T12:00:00`);state.employees.forEach(employee=>{const record=state.weeks[key]?.[employee.employeeId];if(!record)return;const result=calc(employee.employeeId,record,key);rows.push([key,employee.name,num(record.days),num(record.vacation),num(record.hours),num(record.overtime),result.dayPay,result.hourPay,result.overtimePay,result.bonus,result.other,result.income,num(record.payback),num(record.advance),num(record.loan),num(record.repayment),result.cash,num(record.cashbox?.topup),num(record.cashbox?.withdrawal),result.totalCash,result.debt])})})}finally{weekStart=savedStart}if(rows.length===1){toast("Ehhez az időszakhoz még nincs mentett munkabér.");return}const label=scope==="week"?selected:scope==="month"?`${year}-${month}`:String(year),blob=new Blob(["\ufeff"+rows.map(row=>row.map(csvCell).join(";")).join("\r\n")],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`diszkertek-munkaber-${label}.csv`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  function renderTotals(){const totals={income:0,cash:0,topup:0,withdrawal:0,totalCash:0,loan:0,repayment:0,bonus:0};activeEmployees().forEach(e=>{const r=getWeek()[e.employeeId],c=calc(e.employeeId,r);totals.income+=c.income;totals.cash+=c.cash;totals.topup+=num(r.cashbox?.topup);totals.withdrawal+=num(r.cashbox?.withdrawal);totals.totalCash+=c.totalCash;totals.loan+=num(r.loan);totals.repayment+=num(r.repayment);totals.bonus+=c.bonus});const data=[["Összes jövedelem",totals.income,"alert"],["Összes dolgozói készpénz",totals.cash,"success"],["Összes kasszafeltöltés",totals.topup,""],["Összes kasszakivonás",-totals.withdrawal,"alert"],["Készpénz + kassza",totals.totalCash,"success"],["Összes kölcsön",totals.loan,"alert"],["Összes törlesztés",totals.repayment,""],["Összes bónusz",totals.bonus,""]];document.getElementById("weeklyTotals").innerHTML=data.map(x=>`<div class="total ${x[2]}"><span>${x[0]}</span><strong>${fmt(x[1])}</strong></div>`).join("")}

  function renderEmployees(){document.getElementById("employeeSettings").innerHTML=activeEmployees().map(e=>`<article class="setting-card"><div><h3>${esc(e.name)}</h3><p>Napibér: ${fmt(e.dailyRate)} · Órabér: ${fmt(e.hourlyRate)} · Túlóra: ${fmt(e.overtimeRate)}/óra · Szabadság: ${e.vacationAllowance} nap${e.cashier?" · Kasszás":""}</p></div><div><button class="button small secondary" data-edit="${e.employeeId}">Szerkesztés</button> <button class="button small danger" data-delete="${e.employeeId}">Törlés</button></div></article>`).join("");document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>openEmployee(b.dataset.edit));document.querySelectorAll("[data-delete]").forEach(b=>b.onclick=()=>deleteEmployee(b.dataset.delete))}
  function openEmployee(employeeId){const e=state.employees.find(x=>x.employeeId===employeeId)||{employeeId:"",name:"",dailyRate:0,hourlyRate:0,overtimeRate:5000,vacationAllowance:5,cashier:false,workwearMonthly:0,winterMonthly:0},f=document.getElementById("employeeForm");["name","dailyRate","hourlyRate","overtimeRate","vacationAllowance","workwearMonthly","winterMonthly"].forEach(k=>f.elements[k].value=e[k]);f.elements.id.value=e.employeeId;f.elements.cashier.checked=e.cashier;document.getElementById("employeeDialog").showModal()}
  function deleteEmployee(employeeId){const e=state.employees.find(x=>x.employeeId===employeeId);if(!confirm(`Biztosan eltávolítod ${e.name} dolgozót? A korábbi adatai a statisztikában megmaradnak.`))return;e.active=false;save("Dolgozó eltávolítva.");renderEmployees();renderWeek();renderFunds()}
  function fundData(e){return state.funds[e.employeeId]||={workwear:{balance:0,correction:0,purchases:[]},winter:{balance:0,correction:0,payout:0}}}
  function paidFundDays(employeeId){const start=state.fundAccrualStart||"9999-12-31",through=iso(fridayFor(new Date()));return Object.entries(state.weeks||{}).filter(([key])=>key>=start&&key<=through).reduce((sum,[,week])=>sum+num(week[employeeId]?.days)+num(week[employeeId]?.vacation),0)}
  function renderFunds(){document.getElementById("fundCards").innerHTML=activeEmployees().filter(e=>num(e.workwearMonthly)||num(e.winterMonthly)).map(e=>{const f=fundData(e),days=paidFundDays(e.employeeId),workCredit=days*num(e.workwearMonthly),winterCredit=days*num(e.winterMonthly),purchases=(f.workwear.purchases||[]),spent=purchases.reduce((s,p)=>s+num(p.amount),0),workCurrent=signed(f.workwear.balance)+workCredit-spent+signed(f.workwear.correction),winterCurrent=signed(f.winter.balance)+winterCredit-num(f.winter.payout)+signed(f.winter.correction);return `<article class="fund-card" data-fund="${e.employeeId}"><div class="fund-head"><h3>${esc(e.name)}</h3><span>Napi összegek: ${fmt(e.workwearMonthly)} / ${fmt(e.winterMonthly)}</span></div><div class="fund-columns"><section class="fund-box"><h4>Munkaruha</h4><div class="fund-fields"><label>Fennálló egyenleg<input data-work="balance" type="number" value="${f.workwear.balance}"></label><label>Automatikus jóváírás (${days} fizetett nap)<input value="${workCredit}" disabled></label><label>Vásárlások<input value="${spent}" disabled></label><label>Korrekció / hozzáírás<input data-work="correction" type="number" value="${f.workwear.correction}"></label></div><div class="purchase-list">${purchases.map(p=>`<div class="purchase" data-purchase="${p.id}"><input data-p="date" type="date" value="${p.date}"><input data-p="label" value="${esc(p.label)}" placeholder="Megnevezés"><input data-p="amount" type="number" value="${p.amount}" placeholder="Összeg"><button data-p-remove type="button">×</button></div>`).join("")}</div><button class="add-item" data-add-purchase type="button">+ Vásárlás</button><div class="fund-balance">Jelenlegi egyenleg: ${fmt(workCurrent)}</div></section><section class="fund-box"><h4>Téli pénz</h4><div class="fund-fields"><label>Fennálló egyenleg<input data-winter="balance" type="number" value="${f.winter.balance}"></label><label>Automatikus jóváírás (${days} fizetett nap)<input value="${winterCredit}" disabled></label><label>Kifizetés<input data-winter="payout" type="number" value="${f.winter.payout}"></label><label>Korrekció / hozzáírás<input data-winter="correction" type="number" value="${f.winter.correction}"></label></div><div class="fund-balance">Jelenlegi egyenleg: ${fmt(winterCurrent)}</div></section></div></article>`}).join("");bindFunds()}
  function bindFunds(){document.querySelectorAll("[data-fund]").forEach(card=>{const e=state.employees.find(x=>x.employeeId===card.dataset.fund),f=fundData(e);card.querySelectorAll("[data-work]").forEach(i=>i.onchange=()=>{f.workwear[i.dataset.work]=signed(i.value);save();renderFunds()});card.querySelectorAll("[data-winter]").forEach(i=>i.onchange=()=>{f.winter[i.dataset.winter]=signed(i.value);save();renderFunds()});card.querySelector("[data-add-purchase]").onclick=()=>{f.workwear.purchases.push({id:id(),date:iso(new Date()),label:"",amount:0});save();renderFunds()};card.querySelectorAll("[data-purchase]").forEach(row=>{const p=f.workwear.purchases.find(x=>x.id===row.dataset.purchase);row.querySelectorAll("[data-p]").forEach(i=>i.onchange=()=>{p[i.dataset.p]=i.dataset.p==="amount"?num(i.value):i.value;save();renderFunds()});row.querySelector("[data-p-remove]").onclick=()=>{f.workwear.purchases=f.workwear.purchases.filter(x=>x.id!==p.id);save();renderFunds()}})})}

  function renderStatistics(){
    const employeeSelect=document.getElementById("statisticsEmployee"),current=employeeSelect.value;
    employeeSelect.innerHTML='<option value="">Minden dolgozó</option>'+state.employees.map(e=>`<option value="${e.employeeId}">${esc(e.name)}</option>`).join("");employeeSelect.value=current;
    const keys=Object.keys(state.weeks||{}).sort(),yearSelect=document.getElementById("statisticsYear"),monthSelect=document.getElementById("statisticsMonth"),from=document.getElementById("statisticsFrom"),to=document.getElementById("statisticsTo");
    const years=[...new Set(keys.map(key=>key.slice(0,4)))].sort().reverse(),savedYear=yearSelect.value;yearSelect.innerHTML='<option value="">Minden év</option>'+years.map(year=>`<option value="${year}">${year}</option>`).join("");yearSelect.value=years.includes(savedYear)?savedYear:"";
    const selected=employeeSelect.value,year=yearSelect.value,month=monthSelect.value,start=from.value,end=to.value,savedStart=weekStart,closingDebts=new Map(),rows=[],totals={days:0,income:0,cash:0,bonus:0,other:0,payback:0,advance:0,loan:0,repayment:0,topup:0,withdrawal:0,totalCash:0};
    from.disabled=Boolean(year||month);to.disabled=Boolean(year||month);
    try{
      keys.forEach(key=>{const weekEnd=iso(addDays(new Date(`${key}T12:00:00`),6)),matchesYear=!year||key.startsWith(`${year}-`),matchesMonth=!month||key.slice(5,7)===month,matchesDate=Boolean(year||month)||( (!start||weekEnd>=start)&&(!end||key<=end) );if(!matchesYear||!matchesMonth||!matchesDate)return;weekStart=new Date(`${key}T12:00:00`);state.employees.filter(e=>!selected||e.employeeId===selected).forEach(e=>{const r=state.weeks[key]?.[e.employeeId];if(!r)return;const c=calc(e.employeeId,r,key),paid=num(r.days)+num(r.vacation);
        totals.days+=paid;totals.income+=c.income;totals.cash+=c.cash;totals.bonus+=c.bonus;totals.other+=c.other;totals.payback+=num(r.payback);totals.advance+=num(r.advance);totals.loan+=num(r.loan);totals.repayment+=num(r.repayment);totals.topup+=num(r.cashbox?.topup);totals.withdrawal+=num(r.cashbox?.withdrawal);totals.totalCash+=c.totalCash;closingDebts.set(e.employeeId,c.debt)
        rows.push(`<tr><td>${key} – ${weekEnd}</td><td>${esc(e.name)}</td><td>${paid}</td><td>${fmt(c.income)}</td><td>${fmt(c.cash)}</td><td>${fmt(c.bonus)}</td><td>${fmt(c.other)}</td><td>${fmt(r.payback)}</td><td>${fmt(r.advance)}</td><td>${fmt(r.loan)}</td><td>${fmt(r.repayment)}</td><td>${fmt(r.cashbox?.topup)}</td><td>${fmt(r.cashbox?.withdrawal)}</td><td>${fmt(c.totalCash)}</td><td>${fmt(c.debt)}</td></tr>`)
      })})
    }finally{weekStart=savedStart}
    totals.debt=[...closingDebts.values()].reduce((sum,value)=>sum+num(value),0);
    document.getElementById("statisticsSummary").innerHTML=[["Összes jövedelem",fmt(totals.income)],["Dolgozói készpénz",fmt(totals.cash)],["Bónusz",fmt(totals.bonus)],["Egyéb tétel",fmt(totals.other)],["Visszafizetés",fmt(totals.payback)],["Előleg",fmt(totals.advance)],["Kölcsön",fmt(totals.loan)],["Törlesztés",fmt(totals.repayment)],["Kasszafeltöltés",fmt(totals.topup)],["Kasszakivonás",fmt(totals.withdrawal)],["Átadandó végeredmény",fmt(totals.totalCash)],["Fennmaradó tartozás",fmt(totals.debt)]].map(([label,value])=>`<div><span>${label}</span><strong>${value}</strong></div>`).join("");
    document.getElementById("statisticsRows").innerHTML=rows.join("")||'<tr><td colspan="15" class="statistics-empty">Nincs adat a kiválasztott időszakban.</td></tr>';
    document.getElementById("statisticsTotals").innerHTML=`<tr><th>Összesen</th><td></td><td>${totals.days}</td><td>${fmt(totals.income)}</td><td>${fmt(totals.cash)}</td><td>${fmt(totals.bonus)}</td><td>${fmt(totals.other)}</td><td>${fmt(totals.payback)}</td><td>${fmt(totals.advance)}</td><td>${fmt(totals.loan)}</td><td>${fmt(totals.repayment)}</td><td>${fmt(totals.topup)}</td><td>${fmt(totals.withdrawal)}</td><td>${fmt(totals.totalCash)}</td><td>${fmt(totals.debt)}</td></tr>`;
  }

  const actionNames={absence:"Nem dolgozott",halfday:"Fél nap", "paid-leave":"Fizetett szabadság","unpaid-leave":"Fizetetlen szabadnap",rain:"Esős nap","extra-day":"Plusz munkanap",saturday:"Szombati munkanap",hours:"Normál munkaóra",overtime:"Túlóra",bonus:"Bónusz",trip:"Fuvar",advance:"Előleg",loan:"Kölcsön",repayment:"Törlesztés",payback:"Visszafizetés","other-income":"Egyéb bevétel","other-deduction":"Egyéb levonás",custom:"Egyedi esemény"};
  function renderAttendance(){const wrap=document.getElementById("attendanceEmployees");wrap.innerHTML=`<label class="all-workers"><input type="checkbox" data-all-workers> Mindenki</label>${activeEmployees().map(e=>`<label><input type="checkbox" name="workers" value="${e.employeeId}"> ${esc(e.name)}</label>`).join("")}`;wrap.querySelector("[data-all-workers]").onchange=e=>{wrap.querySelectorAll('[name="workers"]').forEach(box=>box.checked=e.target.checked);updateAttendancePreview()};wrap.querySelectorAll('[name="workers"]').forEach(box=>box.onchange=()=>{const boxes=[...wrap.querySelectorAll('[name="workers"]')];wrap.querySelector("[data-all-workers]").checked=boxes.every(x=>x.checked);updateAttendancePreview()});const date=document.getElementById("attendanceDate");if(!date.value)date.value=iso(new Date());updateAttendanceFields();renderDailyEvents()}
  function selectedWorkers(){return [...document.querySelectorAll('#attendanceEmployees [name="workers"]:checked')].map(box=>state.employees.find(e=>e.employeeId===box.value)).filter(Boolean)}
  function updateAttendanceFields(){const action=document.getElementById("attendanceAction").value,form=document.getElementById("attendanceForm"),quantity=["halfday","hours","overtime"].includes(action),amount=["bonus","trip","advance","loan","repayment","payback","other-income","other-deduction","custom"].includes(action),label=["bonus","trip","other-income","other-deduction","custom"].includes(action);document.getElementById("quantityField").hidden=!quantity;document.getElementById("amountField").hidden=!amount;document.getElementById("labelField").hidden=!label;document.getElementById("customFields").hidden=action!=="custom";document.getElementById("quantityLabel").firstChild.textContent=action==="overtime"?"Túlóra (óra)":action==="halfday"?"Ledolgozott órák":"Normál órák";if(action==="halfday"&&!form.elements.quantity.value)form.elements.quantity.value=4;updateAttendancePreview()}
  function updateAttendancePreview(){const workers=selectedWorkers(),action=document.getElementById("attendanceAction").value,form=document.getElementById("attendanceForm"),names=workers.length===activeEmployees().length?"Mindenki":workers.map(e=>e.name).join(", "),preview=document.getElementById("attendancePreview"),ready=Boolean(workers.length&&action);document.getElementById("employeePickerSummary").textContent=workers.length?`${workers.length} dolgozó kiválasztva`:"Dolgozók kiválasztása";preview.hidden=!ready;if(!ready){preview.textContent="";return}const extra=form.elements.quantity.value?` · ${form.elements.quantity.value} óra`:form.elements.amount.value?` · ${fmt(moneyNum(form.elements.amount.value))}`:"";preview.textContent=`${form.elements.date.value} · ${names} · ${actionNames[action]}${extra}`}
  function effectFor(action,form){const q=num(form.elements.quantity.value),amount=moneyNum(form.elements.amount.value),effect={};if(["absence","unpaid-leave","rain"].includes(action))effect.days=-1;if(action==="halfday"){effect.days=-1;effect.hours=q}if(action==="paid-leave"){effect.days=-1;effect.vacation=1}if(["extra-day","saturday"].includes(action))effect.days=1;if(action==="hours")effect.hours=q;if(action==="overtime")effect.overtime=q;if(action==="bonus")effect.bonus=amount;if(["trip","other-income"].includes(action))effect.other=amount;if(action==="advance"||action==="other-deduction")effect.advance=amount;if(action==="loan")effect.loan=amount;if(action==="repayment")effect.repayment=amount;if(action==="payback")effect.payback=amount;if(action==="custom"){effect.days=signed(form.elements.dayDelta.value);effect.hours=num(form.elements.normalHours.value);effect.overtime=num(form.elements.overtimeHours.value);if(form.elements.amountDirection.value==="income")effect.other=amount;else effect.advance=amount}return effect}
  function recordForDate(employee,date){const key=iso(fridayFor(new Date(`${date}T12:00:00`)));state.weeks[key]||={};state.weeks[key][employee.employeeId]||=emptyWeek(employee);return state.weeks[key][employee.employeeId]}
  function applyEvent(event,direction=1){const employee=state.employees.find(e=>e.employeeId===event.employeeId);if(!employee)return;const r=recordForDate(employee,event.date),fx=event.effect||{};["days","hours","overtime","vacation","advance","loan","repayment","payback"].forEach(k=>{if(fx[k])r[k]=Math.max(0,num(r[k])+fx[k]*direction)});if(fx.bonus){if(direction>0)r.bonuses.push({id:event.id,label:event.label||actionNames[event.type],amount:fx.bonus});else r.bonuses=r.bonuses.filter(x=>x.id!==event.id)}if(fx.other){if(direction>0)r.others.push({id:event.id,label:event.label||actionNames[event.type],amount:fx.other});else r.others=r.others.filter(x=>x.id!==event.id)}}
  function renderDailyEvents(){const date=document.getElementById("attendanceDate").value,events=state.events.filter(e=>e.date===date).sort((a,b)=>a.createdAt.localeCompare(b.createdAt)),selectedButton=document.getElementById("deleteSelectedEvents");document.getElementById("dailyLogDate").textContent=new Date(`${date}T12:00:00`).toLocaleDateString("hu-HU",{year:"numeric",month:"long",day:"numeric",weekday:"long"});document.getElementById("dailyEventCount").textContent=`${events.length} esemény`;document.getElementById("deleteDailyEvents").hidden=!events.length;selectedButton.hidden=!events.length;selectedButton.disabled=true;document.getElementById("dailyEvents").innerHTML=events.length?events.map(e=>{const detail=e.label||e.note;return `<article class="daily-event" data-event="${e.id}"><label class="event-selector"><input type="checkbox" data-select-event aria-label="${esc(e.employeeName)} eseményének kijelölése"></label><div><h4>${esc(e.employeeName)} · ${esc(actionNames[e.type]||e.type)}</h4>${detail?`<p>${esc(detail)}</p>`:""}<strong>${eventEffectText(e.effect)}</strong></div><button type="button" data-delete-event>Törlés</button></article>`}).join(""):'<p class="empty-events">Ezen a napon nincs rögzített eltérés.</p>';document.querySelectorAll("[data-select-event]").forEach(input=>input.onchange=()=>{selectedButton.disabled=!document.querySelector("[data-select-event]:checked")});document.querySelectorAll("[data-delete-event]").forEach(button=>button.onclick=()=>{const row=button.closest("[data-event]"),event=state.events.find(e=>e.id===row.dataset.event);if(!confirm("Biztosan törlöd ezt az eseményt?"))return;applyEvent(event,-1);state.events=state.events.filter(e=>e.id!==event.id);save("Esemény törölve.");renderDailyEvents();renderWeek()})}
  function eventEffectText(fx={}){const parts=[];if(fx.days)parts.push(`${fx.days>0?"+":""}${fx.days} nap`);if(fx.hours)parts.push(`+${fx.hours} óra`);if(fx.overtime)parts.push(`+${fx.overtime} túlóra`);if(fx.vacation)parts.push("fizetett nap");if(fx.bonus||fx.other)parts.push(`+${fmt(fx.bonus||fx.other)}`);if(fx.advance||fx.loan||fx.repayment||fx.payback)parts.push(fmt(fx.advance||fx.loan||fx.repayment||fx.payback));return parts.join(" · ")}
  document.getElementById("attendanceAction").onchange=updateAttendanceFields;document.getElementById("attendanceDate").onchange=()=>{renderDailyEvents();updateAttendancePreview()};document.getElementById("attendanceForm").addEventListener("input",updateAttendancePreview);document.getElementById("attendanceForm").addEventListener("submit",event=>{event.preventDefault();const form=event.currentTarget,workers=selectedWorkers(),action=form.elements.action.value;if(!workers.length){toast("Válassz legalább egy dolgozót.");return}const effect=effectFor(action,form);workers.forEach(employee=>{const attendanceEvent={id:id(),date:form.elements.date.value,employeeId:employee.employeeId,employeeName:employee.name,type:action,label:form.elements.label.value.trim(),note:form.elements.note.value.trim(),effect,createdAt:new Date().toISOString()};state.events.push(attendanceEvent);applyEvent(attendanceEvent)});save(`${workers.length} esemény rögzítve.`);const keepDate=form.elements.date.value;form.reset();form.elements.date.value=keepDate;renderAttendance();renderWeek()});
  function deleteAttendanceEvents(events,message){if(!events.length||!confirm(message))return;const ids=new Set(events.map(event=>event.id));events.forEach(event=>applyEvent(event,-1));state.events=state.events.filter(event=>!ids.has(event.id));save(`${events.length} esemény törölve.`);renderDailyEvents();renderWeek()}
  document.getElementById("deleteSelectedEvents").onclick=()=>{const ids=new Set([...document.querySelectorAll("[data-select-event]:checked")].map(input=>input.closest("[data-event]").dataset.event)),events=state.events.filter(event=>ids.has(event.id));deleteAttendanceEvents(events,`Biztosan törlöd a kijelölt ${events.length} eseményt?`)};
  document.getElementById("deleteDailyEvents").onclick=()=>{const date=document.getElementById("attendanceDate").value,events=state.events.filter(e=>e.date===date);deleteAttendanceEvents(events,`Biztosan törlöd mind a(z) ${events.length} eseményt erről a napról?`)};
  document.querySelectorAll(".nav-button[data-view]").forEach(button=>button.onclick=()=>{sessionStorage.setItem("diszkertek-munkaber-active-view",button.dataset.view);document.querySelectorAll(".nav-button[data-view]").forEach(x=>x.classList.toggle("active",x===button));document.querySelectorAll(".view").forEach(v=>v.hidden=v.id!==`${button.dataset.view}View`);if(button.dataset.view==="attendance")renderAttendance();if(button.dataset.view==="employees")renderEmployees();if(button.dataset.view==="funds")renderFunds();if(button.dataset.view==="statistics")renderStatistics()});
  document.getElementById("previousWeek").onclick=()=>{weekStart=addDays(weekStart,-7);renderWeek()};document.getElementById("nextWeek").onclick=()=>{weekStart=addDays(weekStart,7);renderWeek()};document.getElementById("addEmployee").onclick=()=>openEmployee();
  document.getElementById("selectAllCards").addEventListener("change",event=>{document.querySelectorAll("[data-select-card]").forEach(input=>input.checked=event.target.checked);updatePrintSelection()});document.getElementById("printSelected").onclick=()=>printGroup(false);document.getElementById("printAll").onclick=()=>printGroup(true);
  document.querySelectorAll("[data-download-payroll]").forEach(button=>button.onclick=()=>downloadPayroll(button.dataset.downloadPayroll));
  document.getElementById("employeeForm").addEventListener("submit",event=>{event.preventDefault();if(event.submitter?.value!=="save")return;const f=event.currentTarget,data=Object.fromEntries(new FormData(f));let e=state.employees.find(x=>x.employeeId===data.id);if(!e){e={employeeId:id(),active:true};state.employees.push(e)}Object.assign(e,{name:data.name.trim(),dailyRate:num(data.dailyRate),hourlyRate:num(data.hourlyRate),overtimeRate:num(data.overtimeRate),vacationAllowance:num(data.vacationAllowance),workwearMonthly:num(data.workwearMonthly),winterMonthly:num(data.winterMonthly),cashier:f.elements.cashier.checked});save("Dolgozó adatai mentve.");document.getElementById("employeeDialog").close();renderEmployees();renderWeek();renderFunds()});
  document.getElementById("statisticsFilters").addEventListener("input",renderStatistics);
  function applyPayrollSync(data){if(!data)return;state=data;if(migrateState(state))save();renderAttendance();renderWeek();const active=document.querySelector(".nav-button[data-view].active")?.dataset.view;if(active==="employees")renderEmployees();if(active==="funds")renderFunds();if(active==="statistics")renderStatistics()}
  window.applyPayrollSync=applyPayrollSync;
  window.showPayrollToast=toast;
  renderAttendance();renderWeek();const savedView=sessionStorage.getItem("diszkertek-munkaber-active-view"),savedButton=document.querySelector(`.nav-button[data-view="${savedView}"]`);if(savedButton)savedButton.click();
  PayrollStorage.startSync(applyPayrollSync);
}());
