(function () {
  "use strict";
  const money = new Intl.NumberFormat("hu-HU", { maximumFractionDigits: 0 });
  const fmt = value => `${money.format(Math.round(Number(value) || 0))} Ft`;
  const num = value => Math.max(0, Number(value) || 0);
  const signed = value => Number(value) || 0;
  const esc = value => String(value ?? "").replace(/[&<>'"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
  const id = () => `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`;
  const defaults = [
    ["mark","Márk",31000,true,20000,40000],["gabor","Gábor",28000,false,20000,40000],
    ["attila","Attila",26000,false,20000,40000],["adam","Ádám",24000,true,20000,60000],
    ["gyula","Gyula",22000,false,20000,40000],["bendeguz","Bendegúz",25000,true,0,0],
    ["agi","Ági",16000,true,0,0],["tamas","Tamás",40000,false,20000,40000]
  ].map(([employeeId,name,dailyRate,cashier,workwearMonthly,winterMonthly]) => ({employeeId,name,dailyRate,hourlyRate:dailyRate/8,overtimeRate:5000,vacationAllowance:5,cashier,workwearMonthly,winterMonthly}));
  let state = PayrollStorage.load() || {version:1,employees:defaults,weeks:{},funds:{},creditedMonths:{},events:[]};
  state.events ||= [];if(!state.baseDaysV2){Object.values(state.weeks||{}).forEach(week=>Object.values(week).forEach(record=>{if(Number(record.days)===0)record.days=5}));state.baseDaysV2=true}
  let weekStart = fridayFor(new Date());

  function fridayFor(date) { const d = new Date(date); d.setHours(12,0,0,0); const day=d.getDay(); const diff=(day-5+7)%7; d.setDate(d.getDate()-diff); return d; }
  function iso(date) { return date.toISOString().slice(0,10); }
  function addDays(date, days) { const d=new Date(date); d.setDate(d.getDate()+days); return d; }
  function huDate(date) { return date.toLocaleDateString("hu-HU",{month:"2-digit",day:"2-digit"}); }
  function emptyWeek(employee) { return {days:5,hours:0,overtime:0,vacation:0,advance:0,loan:0,repayment:0,payback:0,newDebt:0,bonuses:[],others:[],cashbox:employee.cashier?{opening:0,income:0,expense:0,correction:0,topup:0}:null}; }
  function getWeek(key=iso(weekStart)) { state.weeks[key] ||= {}; state.employees.forEach(e => state.weeks[key][e.employeeId] ||= emptyWeek(e)); return state.weeks[key]; }
  function previousDebt(employeeId) { const keys=Object.keys(state.weeks).filter(k=>k<iso(weekStart)).sort(); if(!keys.length)return 0; return calc(employeeId,state.weeks[keys.at(-1)][employeeId]||{}).debt; }
  function usedVacation(employeeId, year) { return Object.entries(state.weeks).filter(([k])=>k.startsWith(String(year))).reduce((sum,[,w])=>sum+num(w[employeeId]?.vacation),0); }
  function sumItems(items) { return (items||[]).reduce((s,item)=>s+signed(item.amount),0); }
  function calc(employeeId, record) {
    const e=state.employees.find(x=>x.employeeId===employeeId); if(!e)return {};
    const dayPay=(num(record.days)+num(record.vacation))*num(e.dailyRate), hourPay=num(record.hours)*num(e.hourlyRate), overtimePay=num(record.overtime)*num(e.overtimeRate);
    const bonus=sumItems(record.bonuses), other=sumItems(record.others), income=dayPay+hourPay+overtimePay+bonus+other;
    const deductions=num(record.advance)+num(record.repayment)+num(record.payback), cash=Math.max(0,income-deductions);
    const oldDebt=previousDebtRaw(employeeId), debt=Math.max(0,oldDebt+num(record.loan)+num(record.newDebt)-num(record.repayment)-num(record.payback));
    const cb=record.cashbox||{}, current=num(cb.opening)+num(cb.income)-num(cb.expense)+signed(cb.correction), totalCash=cash+num(cb.topup);
    return {dayPay,hourPay,overtimePay,bonus,other,income,deductions,cash,oldDebt,debt,current,totalCash};
  }
  function previousDebtRaw(employeeId) { const keys=Object.keys(state.weeks).filter(k=>k<iso(weekStart)).sort(); if(!keys.length)return 0; const r=state.weeks[keys.at(-1)][employeeId]||{}; const oldKey=weekStart; weekStart=new Date(keys.at(-1)+"T12:00:00"); const result=calc(employeeId,r).debt; weekStart=oldKey; return result; }
  function save(message) { PayrollStorage.save(state); if(message)toast(message); }
  function toast(message){const el=document.getElementById("toast");el.textContent=message;el.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove("show"),2200)}

  function renderWeek() {
    const end=addDays(weekStart,6), pay=addDays(end,1), key=iso(weekStart), records=getWeek(key);
    document.getElementById("weekRange").textContent=`${weekStart.getFullYear()}. ${huDate(weekStart)} – ${huDate(end)}`;
    document.getElementById("payday").textContent=`Fizetés: ${pay.toLocaleDateString("hu-HU")}, péntek`;
    document.getElementById("employeeCards").innerHTML=state.employees.map(e=>card(e,records[e.employeeId],key)).join("");
    document.querySelectorAll(".pay-card .pay-head").forEach(head=>head.insertAdjacentHTML("afterbegin",'<label class="card-selector"><input data-select-card type="checkbox"> Nyomtatásra</label>'));
    bindCards(); bindPrintSelection(); renderTotals(); save();
  }
  function row(label,name,value,rate,total,cls="") { return `<tr class="${cls}"><td>${label}</td><td><input data-field="${name}" type="number" min="0" step="0.5" value="${value||0}" aria-label="${label}"></td><td class="number">${fmt(rate)}</td><td class="number pay-row-total">${fmt(total)}</td></tr>`; }
  function card(e,r,key) {
    const c=calc(e.employeeId,r), vac=usedVacation(e.employeeId,weekStart.getFullYear()), cashbox=e.cashier?`<tr class="cashbox-title"><td colspan="4"><b>Kassza</b></td></tr><tr><td>Indulás</td><td><input data-cash="opening" type="number" value="${r.cashbox?.opening||0}"></td><td>Bevétel</td><td><input data-cash="income" type="number" value="${r.cashbox?.income||0}"></td></tr><tr><td>Kiadás</td><td><input data-cash="expense" type="number" value="${r.cashbox?.expense||0}"></td><td>Jelenleg</td><td class="number">${fmt(c.current)}</td></tr><tr class="cashbox-next"><td>Korrekció</td><td><input data-cash="correction" type="number" value="${r.cashbox?.correction||0}"></td><td>Jövőheti</td><td class="number"><b>${fmt(c.current)}</b></td></tr><tr><td>Kasszafeltöltés</td><td colspan="2"><input data-cash="topup" type="number" min="0" value="${r.cashbox?.topup||0}"></td><td class="number">${fmt(num(r.cashbox?.topup))}</td></tr><tr class="cash-row"><td colspan="3">Pénteken átadandó teljes készpénz</td><td class="number">${fmt(c.totalCash)}</td></tr>`:"";
    return `<article class="pay-card" data-employee="${e.employeeId}"><div class="pay-head"><h2>${esc(e.name)}</h2><div><strong>${weekStart.getFullYear()}</strong><small>${huDate(weekStart)} – ${huDate(addDays(weekStart,6))}</small></div></div><div class="summary-strip"><span>Nap<b>${num(r.days)}</b></span><span>Szabadság<b>${num(r.vacation)} (${vac}/${e.vacationAllowance})</b></span><span>Készpénz<b>${fmt(c.cash)}</b></span></div><table class="pay-table"><thead><tr><th>Tétel</th><th>Db</th><th class="number">Bér</th><th class="number">Összesen</th></tr></thead><tbody>${row("Nap","days",r.days,e.dailyRate,c.dayPay)}${row("Óra","hours",r.hours,e.hourlyRate,c.hourPay)}${row("Túlóra","overtime",r.overtime,e.overtimeRate,c.overtimePay)}${row("Fizetett szabadság","vacation",r.vacation,e.dailyRate,num(r.vacation)*e.dailyRate)}<tr><td>Bónusz</td><td colspan="2">${(r.bonuses||[]).length} tétel</td><td class="number pay-row-total">${fmt(c.bonus)}</td></tr><tr><td>Egyéb tétel</td><td colspan="2">${(r.others||[]).length} tétel</td><td class="number pay-row-total">${fmt(c.other)}</td></tr><tr class="income-row"><td colspan="3">Jövedelem</td><td class="number pay-row-total">${fmt(c.income)}</td></tr><tr><td>Visszafizetés</td><td colspan="2"><input data-field="payback" type="number" min="0" value="${r.payback||0}"></td><td></td></tr><tr><td>Előleg</td><td colspan="2"><input data-field="advance" type="number" min="0" value="${r.advance||0}"></td><td></td></tr><tr><td>Kölcsön</td><td colspan="2"><input data-field="loan" type="number" min="0" value="${r.loan||0}"></td><td></td></tr><tr><td>Törlesztés</td><td colspan="2"><input data-field="repayment" type="number" min="0" value="${r.repayment||0}"></td><td></td></tr><tr class="cash-row"><td colspan="3">Kifizetendő készpénz</td><td class="number">${fmt(c.cash)}</td></tr><tr class="debt-row"><td>Tartozás régi</td><td class="number">${fmt(c.oldDebt)}</td><td>Tartozás új</td><td class="number">${fmt(c.debt)}</td></tr><tr><td>Új tartozás</td><td colspan="2"><input data-field="newDebt" type="number" min="0" value="${r.newDebt||0}"></td><td></td></tr>${cashbox}</tbody></table><details class="details"><summary>Bónuszok és egyéb tételek szerkesztése</summary><div class="details-body"><h3>Bónuszok</h3><div class="item-list" data-list="bonuses">${itemRows(r.bonuses)}</div><button class="add-item" data-add="bonuses" type="button">+ Bónusz</button><h3>Egyéb tételek</h3><div class="item-list" data-list="others">${itemRows(r.others)}</div><button class="add-item" data-add="others" type="button">+ Egyéb tétel</button></div></details><div class="card-actions"><button class="button small secondary" data-print type="button">Nyomtatás</button><button class="button small secondary" data-email type="button">E-mail</button><button class="button small yellow" data-viber type="button">Viber</button></div></article>`;
  }
  function itemRows(items=[]) { return items.map(x=>`<div class="item-row" data-id="${x.id}"><input data-item="label" value="${esc(x.label)}" aria-label="Megnevezés"><input data-item="amount" type="number" value="${signed(x.amount)}" aria-label="Összeg"><button data-remove type="button" aria-label="Törlés">×</button></div>`).join(""); }
  function bindCards(){document.querySelectorAll(".pay-card").forEach(card=>{const employeeId=card.dataset.employee,r=getWeek()[employeeId];card.querySelectorAll("[data-field]").forEach(input=>{input.addEventListener("input",()=>{r[input.dataset.field]=num(input.value);save()});input.addEventListener("change",renderWeek)});card.querySelectorAll("[data-cash]").forEach(input=>{input.addEventListener("input",()=>{r.cashbox||={opening:0,income:0,expense:0,correction:0,topup:0};r.cashbox[input.dataset.cash]=input.dataset.cash==="correction"?signed(input.value):num(input.value);save()});input.addEventListener("change",renderWeek)});card.querySelectorAll("[data-add]").forEach(b=>b.onclick=()=>{r[b.dataset.add].push({id:id(),label:"",amount:0});save();renderWeek();requestAnimationFrame(()=>document.querySelector(`[data-employee="${employeeId}"] details`).open=true)});card.querySelectorAll(".item-row").forEach(row=>{const list=row.closest("[data-list]").dataset.list,item=r[list].find(x=>x.id===row.dataset.id);row.querySelectorAll("[data-item]").forEach(input=>input.onchange=()=>{item[input.dataset.item]=input.dataset.item==="amount"?signed(input.value):input.value.trim();save();renderWeek()});row.querySelector("[data-remove]").onclick=()=>{r[list]=r[list].filter(x=>x.id!==row.dataset.id);save();renderWeek()}});card.querySelector("[data-print]").onclick=()=>printCard(card);card.querySelector("[data-email]").onclick=()=>share(employeeId,"email");card.querySelector("[data-viber]").onclick=()=>share(employeeId,"viber")})}
  function summaryText(employeeId){const e=state.employees.find(x=>x.employeeId===employeeId),c=calc(employeeId,getWeek()[employeeId]);return `Díszkertek munkabér – ${e.name}\n${huDate(weekStart)} – ${huDate(addDays(weekStart,6))}\nJövedelem: ${fmt(c.income)}\nLevonások: ${fmt(c.deductions)}\nKifizetendő készpénz: ${fmt(c.cash)}${e.cashier?`\nKasszafeltöltés: ${fmt(getWeek()[employeeId].cashbox?.topup)}\nÁtadandó összesen: ${fmt(c.totalCash)}`:""}`}
  function share(employeeId,type){const text=summaryText(employeeId),e=state.employees.find(x=>x.employeeId===employeeId);if(type==="email")location.href=`mailto:?subject=${encodeURIComponent(`Munkabér – ${e.name}`)}&body=${encodeURIComponent(text)}`;else location.href=`viber://forward?text=${encodeURIComponent(text)}`}
  function printCard(card){document.body.classList.add("print-single");card.classList.add("print-target");window.print();setTimeout(()=>{document.body.classList.remove("print-single");card.classList.remove("print-target")},400)}
  function bindPrintSelection(){document.querySelectorAll("[data-select-card]").forEach(input=>input.addEventListener("change",updatePrintSelection));updatePrintSelection()}
  function updatePrintSelection(){const boxes=[...document.querySelectorAll("[data-select-card]")],selected=boxes.filter(x=>x.checked).length;document.getElementById("selectedCount").textContent=`${selected} bérlap kijelölve`;document.getElementById("printSelected").disabled=!selected;document.getElementById("selectAllCards").checked=Boolean(boxes.length)&&selected===boxes.length;document.getElementById("selectAllCards").indeterminate=selected>0&&selected<boxes.length}
  function printGroup(all){const cards=[...document.querySelectorAll(".pay-card")];cards.forEach(card=>card.classList.toggle("print-target",all||card.querySelector("[data-select-card]").checked));document.body.classList.add("print-selected");window.print();setTimeout(()=>{document.body.classList.remove("print-selected");cards.forEach(card=>card.classList.remove("print-target"))},400)}
  function renderTotals(){const totals={income:0,cash:0,topup:0,loan:0,repayment:0,bonus:0};state.employees.forEach(e=>{const r=getWeek()[e.employeeId],c=calc(e.employeeId,r);totals.income+=c.income;totals.cash+=c.cash;totals.topup+=num(r.cashbox?.topup);totals.loan+=num(r.loan);totals.repayment+=num(r.repayment);totals.bonus+=c.bonus});const data=[["Összes jövedelem",totals.income,"alert"],["Összes dolgozói készpénz",totals.cash,"success"],["Összes kasszafeltöltés",totals.topup,""],["Készpénz + kassza",totals.cash+totals.topup,"success"],["Összes kölcsön",totals.loan,"alert"],["Összes törlesztés",totals.repayment,""],["Összes bónusz",totals.bonus,""]];document.getElementById("weeklyTotals").innerHTML=data.map(x=>`<div class="total ${x[2]}"><span>${x[0]}</span><strong>${fmt(x[1])}</strong></div>`).join("")}

  function renderEmployees(){document.getElementById("employeeSettings").innerHTML=state.employees.map(e=>`<article class="setting-card"><div><h3>${esc(e.name)}</h3><p>Napibér: ${fmt(e.dailyRate)} · Órabér: ${fmt(e.hourlyRate)} · Túlóra: ${fmt(e.overtimeRate)}/óra · Szabadság: ${e.vacationAllowance} nap${e.cashier?" · Kasszás":""}</p></div><div><button class="button small secondary" data-edit="${e.employeeId}">Szerkesztés</button> <button class="button small danger" data-delete="${e.employeeId}">Törlés</button></div></article>`).join("");document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>openEmployee(b.dataset.edit));document.querySelectorAll("[data-delete]").forEach(b=>b.onclick=()=>deleteEmployee(b.dataset.delete))}
  function openEmployee(employeeId){const e=state.employees.find(x=>x.employeeId===employeeId)||{employeeId:"",name:"",dailyRate:0,hourlyRate:0,overtimeRate:5000,vacationAllowance:5,cashier:false,workwearMonthly:0,winterMonthly:0},f=document.getElementById("employeeForm");["name","dailyRate","hourlyRate","overtimeRate","vacationAllowance","workwearMonthly","winterMonthly"].forEach(k=>f.elements[k].value=e[k]);f.elements.id.value=e.employeeId;f.elements.cashier.checked=e.cashier;document.getElementById("employeeDialog").showModal()}
  function deleteEmployee(employeeId){const e=state.employees.find(x=>x.employeeId===employeeId);if(!confirm(`Biztosan törlöd ${e.name} dolgozót? A korábbi heti adatai is elérhetetlenné válnak.`))return;state.employees=state.employees.filter(x=>x.employeeId!==employeeId);save("Dolgozó törölve.");renderEmployees();renderWeek();renderFunds()}
  function applyMonthlyCredits(){const today=new Date(), last=new Date(today.getFullYear(),today.getMonth()+1,0);if(today.getDate()!==last.getDate())return;const month=`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,"0")}`;state.creditedMonths[month]||={};state.employees.forEach(e=>{if(state.creditedMonths[month][e.employeeId])return;const f=state.funds[e.employeeId]||={workwear:{balance:0,correction:0,purchases:[]},winter:{balance:0,correction:0,payout:0}};f.workwear.balance+=num(e.workwearMonthly);f.winter.balance+=num(e.winterMonthly);state.creditedMonths[month][e.employeeId]=true});save()}
  function fundData(e){return state.funds[e.employeeId]||={workwear:{balance:0,correction:0,purchases:[]},winter:{balance:0,correction:0,payout:0}}}
  function renderFunds(){document.getElementById("fundCards").innerHTML=state.employees.map(e=>{const f=fundData(e),purchases=(f.workwear.purchases||[]),spent=purchases.reduce((s,p)=>s+num(p.amount),0),workCurrent=num(f.workwear.balance)-spent+signed(f.workwear.correction),winterCurrent=num(f.winter.balance)-num(f.winter.payout)+signed(f.winter.correction);return `<article class="fund-card" data-fund="${e.employeeId}"><div class="fund-head"><h3>${esc(e.name)}</h3><span>Havi keretek: ${fmt(e.workwearMonthly)} / ${fmt(e.winterMonthly)}</span></div><div class="fund-columns"><section class="fund-box"><h4>Munkaruha</h4><div class="fund-fields"><label>Előző egyenleg<input data-work="balance" type="number" value="${f.workwear.balance}"></label><label>Havi jóváírás<input value="${e.workwearMonthly}" disabled></label><label>Vásárlások<input value="${spent}" disabled></label><label>Korrekció<input data-work="correction" type="number" value="${f.workwear.correction}"></label></div><div class="purchase-list">${purchases.map(p=>`<div class="purchase" data-purchase="${p.id}"><input data-p="date" type="date" value="${p.date}"><input data-p="label" value="${esc(p.label)}" placeholder="Megnevezés"><input data-p="amount" type="number" value="${p.amount}" placeholder="Összeg"><button data-p-remove type="button">×</button></div>`).join("")}</div><button class="add-item" data-add-purchase type="button">+ Vásárlás</button><div class="fund-balance">Jelenlegi egyenleg: ${fmt(workCurrent)}</div></section><section class="fund-box"><h4>Téli pénz</h4><div class="fund-fields"><label>Előző egyenleg<input data-winter="balance" type="number" value="${f.winter.balance}"></label><label>Havi jóváírás<input value="${e.winterMonthly}" disabled></label><label>Kifizetés<input data-winter="payout" type="number" value="${f.winter.payout}"></label><label>Korrekció<input data-winter="correction" type="number" value="${f.winter.correction}"></label></div><div class="fund-balance">Jelenlegi egyenleg: ${fmt(winterCurrent)}</div></section></div></article>`}).join("");bindFunds()}
  function bindFunds(){document.querySelectorAll("[data-fund]").forEach(card=>{const e=state.employees.find(x=>x.employeeId===card.dataset.fund),f=fundData(e);card.querySelectorAll("[data-work]").forEach(i=>i.onchange=()=>{f.workwear[i.dataset.work]=signed(i.value);save();renderFunds()});card.querySelectorAll("[data-winter]").forEach(i=>i.onchange=()=>{f.winter[i.dataset.winter]=signed(i.value);save();renderFunds()});card.querySelector("[data-add-purchase]").onclick=()=>{f.workwear.purchases.push({id:id(),date:iso(new Date()),label:"",amount:0});save();renderFunds()};card.querySelectorAll("[data-purchase]").forEach(row=>{const p=f.workwear.purchases.find(x=>x.id===row.dataset.purchase);row.querySelectorAll("[data-p]").forEach(i=>i.onchange=()=>{p[i.dataset.p]=i.dataset.p==="amount"?num(i.value):i.value;save();renderFunds()});row.querySelector("[data-p-remove]").onclick=()=>{f.workwear.purchases=f.workwear.purchases.filter(x=>x.id!==p.id);save();renderFunds()}})})}

  const actionNames={absence:"Nem dolgozott",halfday:"Fél nap", "paid-leave":"Fizetett szabadság","unpaid-leave":"Fizetetlen szabadnap",rain:"Esős nap","extra-day":"Plusz munkanap",saturday:"Szombati munkanap",hours:"Normál munkaóra",overtime:"Túlóra",bonus:"Bónusz",trip:"Fuvar",advance:"Előleg",loan:"Kölcsön",repayment:"Törlesztés",payback:"Visszafizetés","other-income":"Egyéb bevétel","other-deduction":"Egyéb levonás",custom:"Egyedi esemény"};
  function renderAttendance(){const wrap=document.getElementById("attendanceEmployees");wrap.innerHTML=`<label class="all-workers"><input type="checkbox" data-all-workers> Mindenki</label>${state.employees.map(e=>`<label><input type="checkbox" name="workers" value="${e.employeeId}"> ${esc(e.name)}</label>`).join("")}`;wrap.querySelector("[data-all-workers]").onchange=e=>{wrap.querySelectorAll('[name="workers"]').forEach(box=>box.checked=e.target.checked);updateAttendancePreview()};wrap.querySelectorAll('[name="workers"]').forEach(box=>box.onchange=()=>{const boxes=[...wrap.querySelectorAll('[name="workers"]')];wrap.querySelector("[data-all-workers]").checked=boxes.every(x=>x.checked);updateAttendancePreview()});const date=document.getElementById("attendanceDate");if(!date.value)date.value=iso(new Date());updateAttendanceFields();renderDailyEvents()}
  function selectedWorkers(){return [...document.querySelectorAll('#attendanceEmployees [name="workers"]:checked')].map(box=>state.employees.find(e=>e.employeeId===box.value)).filter(Boolean)}
  function updateAttendanceFields(){const action=document.getElementById("attendanceAction").value,form=document.getElementById("attendanceForm"),quantity=["halfday","hours","overtime"].includes(action),amount=["bonus","trip","advance","loan","repayment","payback","other-income","other-deduction","custom"].includes(action),label=["bonus","trip","other-income","other-deduction","custom"].includes(action);document.getElementById("quantityField").hidden=!quantity;document.getElementById("amountField").hidden=!amount;document.getElementById("labelField").hidden=!label;document.getElementById("customFields").hidden=action!=="custom";document.getElementById("quantityLabel").firstChild.textContent=action==="overtime"?"Túlóra (óra)":action==="halfday"?"Ledolgozott órák":"Normál órák";if(action==="halfday"&&!form.elements.quantity.value)form.elements.quantity.value=4;updateAttendancePreview()}
  function updateAttendancePreview(){const workers=selectedWorkers(),action=document.getElementById("attendanceAction").value,form=document.getElementById("attendanceForm"),names=workers.length===state.employees.length?"Mindenki":workers.map(e=>e.name).join(", ");document.getElementById("employeePickerSummary").textContent=workers.length?`${workers.length} dolgozó kiválasztva`:"Dolgozók kiválasztása";const extra=form.elements.quantity.value?` · ${form.elements.quantity.value} óra`:form.elements.amount.value?` · ${fmt(form.elements.amount.value)}`:"";document.getElementById("attendancePreview").textContent=workers.length&&action?`${form.elements.date.value} · ${names} · ${actionNames[action]}${extra}`:"Válassz dolgozót és eseményt."}
  function effectFor(action,form){const q=num(form.elements.quantity.value),amount=num(form.elements.amount.value),effect={};if(["absence","unpaid-leave","rain"].includes(action))effect.days=-1;if(action==="halfday"){effect.days=-1;effect.hours=q}if(action==="paid-leave")effect.vacation=1;if(["extra-day","saturday"].includes(action))effect.days=1;if(action==="hours")effect.hours=q;if(action==="overtime")effect.overtime=q;if(action==="bonus")effect.bonus=amount;if(["trip","other-income"].includes(action))effect.other=amount;if(action==="advance"||action==="other-deduction")effect.advance=amount;if(action==="loan")effect.loan=amount;if(action==="repayment")effect.repayment=amount;if(action==="payback")effect.payback=amount;if(action==="custom"){effect.days=signed(form.elements.dayDelta.value);effect.hours=num(form.elements.normalHours.value);effect.overtime=num(form.elements.overtimeHours.value);if(form.elements.amountDirection.value==="income")effect.other=amount;else effect.advance=amount}return effect}
  function recordForDate(employee,date){const key=iso(fridayFor(new Date(`${date}T12:00:00`)));state.weeks[key]||={};state.weeks[key][employee.employeeId]||=emptyWeek(employee);return state.weeks[key][employee.employeeId]}
  function applyEvent(event,direction=1){const employee=state.employees.find(e=>e.employeeId===event.employeeId);if(!employee)return;const r=recordForDate(employee,event.date),fx=event.effect||{};["days","hours","overtime","vacation","advance","loan","repayment","payback"].forEach(k=>{if(fx[k])r[k]=Math.max(0,num(r[k])+fx[k]*direction)});if(fx.bonus){if(direction>0)r.bonuses.push({id:event.id,label:event.label||actionNames[event.type],amount:fx.bonus});else r.bonuses=r.bonuses.filter(x=>x.id!==event.id)}if(fx.other){if(direction>0)r.others.push({id:event.id,label:event.label||actionNames[event.type],amount:fx.other});else r.others=r.others.filter(x=>x.id!==event.id)}}
  function renderDailyEvents(){const date=document.getElementById("attendanceDate").value,events=state.events.filter(e=>e.date===date).sort((a,b)=>a.createdAt.localeCompare(b.createdAt)),selectedButton=document.getElementById("deleteSelectedEvents");document.getElementById("dailyLogDate").textContent=new Date(`${date}T12:00:00`).toLocaleDateString("hu-HU",{year:"numeric",month:"long",day:"numeric",weekday:"long"});document.getElementById("dailyEventCount").textContent=`${events.length} esemény`;document.getElementById("deleteDailyEvents").hidden=!events.length;selectedButton.hidden=!events.length;selectedButton.disabled=true;document.getElementById("dailyEvents").innerHTML=events.length?events.map(e=>`<article class="daily-event" data-event="${e.id}"><label class="event-selector"><input type="checkbox" data-select-event aria-label="${esc(e.employeeName)} eseményének kijelölése"></label><div><h4>${esc(e.employeeName)} · ${esc(actionNames[e.type]||e.type)}</h4><p>${esc(e.label||e.note||"Nincs megjegyzés")}</p><strong>${eventEffectText(e.effect)}</strong></div><button type="button" data-delete-event>Törlés</button></article>`).join(""):'<p class="empty-events">Ezen a napon nincs rögzített eltérés.</p>';document.querySelectorAll("[data-select-event]").forEach(input=>input.onchange=()=>{selectedButton.disabled=!document.querySelector("[data-select-event]:checked")});document.querySelectorAll("[data-delete-event]").forEach(button=>button.onclick=()=>{const row=button.closest("[data-event]"),event=state.events.find(e=>e.id===row.dataset.event);if(!confirm("Biztosan törlöd ezt az eseményt?"))return;applyEvent(event,-1);state.events=state.events.filter(e=>e.id!==event.id);save("Esemény törölve.");renderDailyEvents();renderWeek()})}
  function eventEffectText(fx={}){const parts=[];if(fx.days)parts.push(`${fx.days>0?"+":""}${fx.days} nap`);if(fx.hours)parts.push(`+${fx.hours} óra`);if(fx.overtime)parts.push(`+${fx.overtime} túlóra`);if(fx.vacation)parts.push("fizetett nap");if(fx.bonus||fx.other)parts.push(`+${fmt(fx.bonus||fx.other)}`);if(fx.advance||fx.loan||fx.repayment||fx.payback)parts.push(fmt(fx.advance||fx.loan||fx.repayment||fx.payback));return parts.join(" · ")}
  document.getElementById("attendanceAction").onchange=updateAttendanceFields;document.getElementById("attendanceDate").onchange=()=>{renderDailyEvents();updateAttendancePreview()};document.getElementById("attendanceForm").addEventListener("input",updateAttendancePreview);document.getElementById("attendanceForm").addEventListener("submit",event=>{event.preventDefault();const form=event.currentTarget,workers=selectedWorkers(),action=form.elements.action.value;if(!workers.length){toast("Válassz legalább egy dolgozót.");return}const effect=effectFor(action,form);workers.forEach(employee=>{const attendanceEvent={id:id(),date:form.elements.date.value,employeeId:employee.employeeId,employeeName:employee.name,type:action,label:form.elements.label.value.trim(),note:form.elements.note.value.trim(),effect,createdAt:new Date().toISOString()};state.events.push(attendanceEvent);applyEvent(attendanceEvent)});save(`${workers.length} esemény rögzítve.`);const keepDate=form.elements.date.value;form.reset();form.elements.date.value=keepDate;renderAttendance();renderWeek()});
  function deleteAttendanceEvents(events,message){if(!events.length||!confirm(message))return;const ids=new Set(events.map(event=>event.id));events.forEach(event=>applyEvent(event,-1));state.events=state.events.filter(event=>!ids.has(event.id));save(`${events.length} esemény törölve.`);renderDailyEvents();renderWeek()}
  document.getElementById("deleteSelectedEvents").onclick=()=>{const ids=new Set([...document.querySelectorAll("[data-select-event]:checked")].map(input=>input.closest("[data-event]").dataset.event)),events=state.events.filter(event=>ids.has(event.id));deleteAttendanceEvents(events,`Biztosan törlöd a kijelölt ${events.length} eseményt?`)};
  document.getElementById("deleteDailyEvents").onclick=()=>{const date=document.getElementById("attendanceDate").value,events=state.events.filter(e=>e.date===date);deleteAttendanceEvents(events,`Biztosan törlöd mind a(z) ${events.length} eseményt erről a napról?`)};
  document.querySelectorAll(".nav-button[data-view]").forEach(button=>button.onclick=()=>{document.querySelectorAll(".nav-button[data-view]").forEach(x=>x.classList.toggle("active",x===button));document.querySelectorAll(".view").forEach(v=>v.hidden=v.id!==`${button.dataset.view}View`);if(button.dataset.view==="attendance")renderAttendance();if(button.dataset.view==="employees")renderEmployees();if(button.dataset.view==="funds")renderFunds()});
  document.getElementById("previousWeek").onclick=()=>{weekStart=addDays(weekStart,-7);renderWeek()};document.getElementById("nextWeek").onclick=()=>{weekStart=addDays(weekStart,7);renderWeek()};document.getElementById("addEmployee").onclick=()=>openEmployee();
  document.getElementById("selectAllCards").addEventListener("change",event=>{document.querySelectorAll("[data-select-card]").forEach(input=>input.checked=event.target.checked);updatePrintSelection()});document.getElementById("printSelected").onclick=()=>printGroup(false);document.getElementById("printAll").onclick=()=>printGroup(true);
  document.getElementById("employeeForm").addEventListener("submit",event=>{event.preventDefault();if(event.submitter?.value!=="save")return;const f=event.currentTarget,data=Object.fromEntries(new FormData(f));let e=state.employees.find(x=>x.employeeId===data.id);if(!e){e={employeeId:id()};state.employees.push(e)}Object.assign(e,{name:data.name.trim(),dailyRate:num(data.dailyRate),hourlyRate:num(data.hourlyRate),overtimeRate:num(data.overtimeRate),vacationAllowance:num(data.vacationAllowance),workwearMonthly:num(data.workwearMonthly),winterMonthly:num(data.winterMonthly),cashier:f.elements.cashier.checked});save("Dolgozó adatai mentve.");document.getElementById("employeeDialog").close();renderEmployees();renderWeek();renderFunds()});
  applyMonthlyCredits();renderAttendance();renderWeek();
  PayrollStorage.startSync(()=>location.reload());
}());
