(function(){
  const KEY="diszkertek-munkaber-v1",PENDING="diszkertek-munkaber-records-pending-v1",DEVICE="diszkertek-munkaber-device-v1",config=window.MUNKABER_SUPABASE||{};
  let baseline=new Map(),saveTimer,syncing=false,started=false;
  const load=()=>{try{return JSON.parse(localStorage.getItem(KEY))}catch(_){return null}};
  const same=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
  async function call(action,data={}){const token=localStorage.getItem(DEVICE),response=await fetch(`${config.url}/functions/v1/munkaber-sync`,{method:"POST",headers:{apikey:config.publishableKey,"Content-Type":"application/json",...(token?{"x-munkaber-token":token}:{})},body:JSON.stringify({action,...data})}),result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||`Munkabér-kapcsolati hiba (${response.status}).`);return result}
  async function connect(manager,pin){const result=await call("login",{manager,pin});if(!result.token)throw new Error("Az eszköz engedélyezése sikertelen.");localStorage.setItem(DEVICE,result.token);return true}
  function flatten(state){const map=new Map(),put=(kind,key,data)=>map.set(`${kind}|${key}`,{kind,key,data});put("meta","main",{version:state.version||1,baseDaysV2:Boolean(state.baseDaysV2),creditedMonths:state.creditedMonths||{},employeeOrder:(state.employees||[]).map(e=>e.employeeId)});(state.employees||[]).forEach(e=>put("employee",e.employeeId,e));Object.entries(state.weeks||{}).forEach(([week,records])=>Object.entries(records).forEach(([employeeId,data])=>put("week",`${week}|${employeeId}`,data)));(state.events||[]).forEach(event=>put("event",event.id,event));Object.entries(state.funds||{}).forEach(([employeeId,data])=>put("fund",employeeId,data));return map}
  function fromRows(rows){const active=(rows||[]).filter(row=>!row.deleted),meta=active.find(row=>row.kind==="meta"&&row.record_key==="main")?.data||{},state={version:meta.version||1,baseDaysV2:Boolean(meta.baseDaysV2),creditedMonths:meta.creditedMonths||{},employees:[],weeks:{},events:[],funds:{}};active.forEach(row=>{if(row.kind==="employee")state.employees.push(row.data);if(row.kind==="week"){const split=row.record_key.indexOf("|");if(split>0){const week=row.record_key.slice(0,split),employeeId=row.record_key.slice(split+1);state.weeks[week]||={};state.weeks[week][employeeId]=row.data}}if(row.kind==="event")state.events.push(row.data);if(row.kind==="fund")state.funds[row.record_key]=row.data});const order=new Map((meta.employeeOrder||[]).map((id,index)=>[id,index]));state.employees.sort((a,b)=>(order.get(a.employeeId)??999)-(order.get(b.employeeId)??999)||a.name.localeCompare(b.name,"hu"));state.events.sort((a,b)=>String(a.createdAt||"").localeCompare(String(b.createdAt||"")));return state}
  function rememberRows(rows){baseline=new Map((rows||[]).map(row=>[`${row.kind}|${row.record_key}`,{kind:row.kind,key:row.record_key,data:row.data,deleted:Boolean(row.deleted)}]))}
  function changesFor(state){const current=flatten(state),changes=[];current.forEach((row,id)=>{const old=baseline.get(id);if(!old||old.deleted||!same(old.data,row.data))changes.push(row)});baseline.forEach((old,id)=>{if(!old.deleted&&!current.has(id))changes.push({kind:old.kind,key:old.key,data:{},deleted:true})});return changes}
  function acceptChanges(changes){changes.forEach(row=>baseline.set(`${row.kind}|${row.key}`,{...row,deleted:Boolean(row.deleted)}))}
  async function push(state){if(syncing||!localStorage.getItem(DEVICE))return;const changes=changesFor(state);if(!changes.length){localStorage.removeItem(PENDING);return}syncing=true;try{await call("save",{records:changes});acceptChanges(changes);localStorage.removeItem(PENDING)}finally{syncing=false}}
  function save(state){localStorage.setItem(KEY,JSON.stringify(state));localStorage.setItem(PENDING,"1");clearTimeout(saveTimer);saveTimer=setTimeout(()=>push(state).catch(error=>console.warn(error.message)),700)}
  async function refresh(onRemoteLoaded,initial=false){if(syncing||!localStorage.getItem(DEVICE)||document.hidden)return;syncing=true;try{const result=await call("load"),rows=result.records||[],remote=fromRows(rows),local=load();rememberRows(rows);if(initial&&local&&localStorage.getItem(PENDING)){syncing=false;await push(local);return}if(!localStorage.getItem(PENDING)&&!same(remote,local)){localStorage.setItem(KEY,JSON.stringify(remote));onRemoteLoaded?.(remote)}}finally{syncing=false}}
  async function startSync(onRemoteLoaded){if(!localStorage.getItem(DEVICE)||started)return;started=true;try{await refresh(onRemoteLoaded,true)}catch(error){console.warn(error.message)}setInterval(()=>refresh(onRemoteLoaded).catch(error=>console.warn(error.message)),30000);addEventListener("focus",()=>refresh(onRemoteLoaded).catch(error=>console.warn(error.message)))}
  window.PayrollStorage={load,save,startSync,connect,hasDevice:()=>Boolean(localStorage.getItem(DEVICE)),key:KEY};
}());
