(function(){
  const KEY="diszkertek-munkaber-v1",DIRTY="diszkertek-munkaber-cloud-pending-v1",DEVICE="diszkertek-munkaber-device-v1",config=window.MUNKABER_SUPABASE||{};
  let saveTimer,lastCloudState="";
  const load=()=>{try{return JSON.parse(localStorage.getItem(KEY))}catch(_){return null}};
  function setStatus(text,type=""){const el=document.getElementById("syncStatus");if(el){el.textContent=text;el.dataset.status=type}}
  async function call(action,data={}){const token=localStorage.getItem(DEVICE),response=await fetch(`${config.url}/functions/v1/munkaber-sync`,{method:"POST",headers:{apikey:config.publishableKey,"Content-Type":"application/json",...(token?{"x-munkaber-token":token}:{})},body:JSON.stringify({action,...data})}),result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||`Munkabér-kapcsolati hiba (${response.status}).`);return result}
  async function connect(manager,pin){const result=await call("login",{manager,pin});if(!result.token)throw new Error("Az eszköz engedélyezése sikertelen.");localStorage.setItem(DEVICE,result.token);return true}
  async function push(data){const serialized=JSON.stringify(data);if(serialized===lastCloudState)return;setStatus("Mentés…","saving");await call("save",{data});lastCloudState=serialized;localStorage.removeItem(DIRTY);setStatus("Felhőbe mentve","online")}
  function save(data){localStorage.setItem(KEY,JSON.stringify(data));localStorage.setItem(DIRTY,"1");clearTimeout(saveTimer);saveTimer=setTimeout(()=>push(data).catch(error=>{console.warn(error.message);setStatus("Helyben mentve","offline")}),900)}
  async function startSync(onRemoteLoaded){if(!localStorage.getItem(DEVICE)){setStatus("Helyi mentés","offline");return}setStatus("Szinkronizálás…","saving");try{const result=await call("load"),remote=result.row?.data,local=load();if(local&&localStorage.getItem(DIRTY)){await push(local);return}if(remote&&JSON.stringify(remote)!==JSON.stringify(local)){localStorage.setItem(KEY,JSON.stringify(remote));lastCloudState=JSON.stringify(remote);setStatus("Felhőből betöltve","online");onRemoteLoaded?.();return}if(!remote&&local)await push(local);else{lastCloudState=remote?JSON.stringify(remote):"";setStatus("Felhőhöz kapcsolódva","online")}}catch(error){console.warn(error.message);setStatus("Helyi mentés","offline")}}
  window.PayrollStorage={load,save,startSync,connect,hasDevice:()=>Boolean(localStorage.getItem(DEVICE)),key:KEY};
}());
